using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("GootenTag")]
[assembly: AssemblyDescriptionAttribute("ASP.NET Helpers for Google tracking (Google Analytics, Google Tag Manager, Google" +
    " Adwords)")]
[assembly: AssemblyCopyrightAttribute("Copyright David Duffett 2014")]
[assembly: AssemblyVersionAttribute("1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0")]

